"""Dataset v4 scenario definitions and latent behaviour specifications.

Dataset v4 is engineered to remediate the blind evaluation failures:
1. Densely models legitimate repeated-failure scenarios (subscription dunning,
   network retry storms, persistent card declines) with card_diversity = 1.
2. Densely models weak-guest and distributed card-testing bot attacks.
3. Decouples customer_id presence from attack probability.
4. Embodies deliberate covariate shift combinations across customer age,
   device age, session age, and attempt cadence variability.
5. Declares 20 matched counterfactual twin pairs for causal evaluation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np

Range = tuple[float, float]

CRITICAL_SCENARIOS = (
    "cross_device_weak_guest",
    "cross_device_partial",
    "distributed_bot_campaign",
    "subscription_dunning_hard",
    "persistent_card_problem_hard",
    "network_retry_storm_hard",
    "shared_household_device",
    "cgnat_mobile_ip_storm",
)


@dataclass(frozen=True)
class ScenarioV4:
    name: str
    population: str  # "attack" | "legitimate"
    weight: float
    episodes: tuple[int, int]
    episode_gap_days: Range
    attempts: tuple[int, int]
    gap_seconds: Range
    gap_spread: Range
    method_validity: Range
    network_instability: Range
    session_rotation: Range
    ip_rotation: Range
    instrument_reuse: Range
    checkout_completion: Range
    continue_after_success: Range
    devices: tuple[int, int]
    device_mode: str  # "sticky" | "spread"
    customers_on_device: tuple[int, int]
    ip_pool: str  # "private" | "shared" | "mobile"
    login_multiplier: Range
    guest: bool
    amount_style_weights: dict[str, float]
    merchant_kinds: tuple[str, ...] | None = None
    prefers_campaign: bool = False
    card_diversity_mode: str = "normal"  # "single_card" | "high_rotation" | "wallet_cycle" | "normal"
    age_pairing: str = "natural"  # "natural" | "old_cust_new_dev" | "new_cust_old_dev" | "established_burst"

    @property
    def label(self) -> int:
        return int(self.population == "attack")


SCENARIOS_V4: dict[str, ScenarioV4] = {
    # --------------------------------------------------------------------------
    # HIGH-PRIORITY ATTACK FAMILIES
    # --------------------------------------------------------------------------
    "cross_device_weak_guest": ScenarioV4(
        name="cross_device_weak_guest",
        population="attack",
        weight=12.0,
        episodes=(1, 3),
        episode_gap_days=(0.01, 0.5),
        attempts=(2, 4),
        gap_seconds=(2.0, 45.0),
        gap_spread=(0.15, 0.45),
        method_validity=(0.02, 0.15),
        network_instability=(0.01, 0.05),
        session_rotation=(0.85, 1.00),
        ip_rotation=(0.75, 1.00),
        instrument_reuse=(0.00, 0.10),
        checkout_completion=(0.00, 0.10),
        continue_after_success=(0.90, 1.00),
        devices=(4, 8),
        device_mode="spread",
        customers_on_device=(1, 1),
        ip_pool="shared",
        login_multiplier=(0.0, 0.0),
        guest=True,
        amount_style_weights={"low": 0.70, "repeat": 0.20, "merchant_typical": 0.10},
        card_diversity_mode="high_rotation",
    ),
    "cross_device_partial": ScenarioV4(
        name="cross_device_partial",
        population="attack",
        weight=10.0,
        episodes=(2, 4),
        episode_gap_days=(0.05, 1.5),
        attempts=(2, 5),
        gap_seconds=(5.0, 120.0),
        gap_spread=(0.20, 0.60),
        method_validity=(0.05, 0.25),
        network_instability=(0.02, 0.08),
        session_rotation=(0.40, 0.75),
        ip_rotation=(0.30, 0.70),
        instrument_reuse=(0.05, 0.20),
        checkout_completion=(0.10, 0.35),
        continue_after_success=(0.85, 0.98),
        devices=(3, 6),
        device_mode="spread",
        customers_on_device=(1, 2),
        ip_pool="shared",
        login_multiplier=(0.4, 0.8),
        guest=False,
        amount_style_weights={"low": 0.50, "merchant_typical": 0.35, "repeat": 0.15},
        card_diversity_mode="high_rotation",
    ),
    "distributed_bot_campaign": ScenarioV4(
        name="distributed_bot_campaign",
        population="attack",
        weight=10.0,
        episodes=(50, 50),
        episode_gap_days=(0.0005, 0.001),
        attempts=(1, 1),
        gap_seconds=(1.0, 20.0),
        gap_spread=(0.10, 0.30),
        method_validity=(0.01, 0.12),
        network_instability=(0.01, 0.04),
        session_rotation=(0.90, 1.00),
        ip_rotation=(0.80, 1.00),
        instrument_reuse=(0.00, 0.05),
        checkout_completion=(0.00, 0.05),
        continue_after_success=(0.95, 1.00),
        devices=(50, 50),
        device_mode="spread",
        customers_on_device=(1, 1),
        ip_pool="mobile",
        login_multiplier=(0.0, 0.2),
        guest=True,
        amount_style_weights={"low": 0.80, "repeat": 0.20},
        card_diversity_mode="high_rotation",
    ),
    "burst_pause_burst_v4": ScenarioV4(
        name="burst_pause_burst_v4",
        population="attack",
        weight=6.0,
        episodes=(2, 4),
        episode_gap_days=(0.2, 1.5),
        attempts=(4, 9),
        gap_seconds=(3.0, 30.0),
        gap_spread=(0.20, 0.50),
        method_validity=(0.02, 0.18),
        network_instability=(0.01, 0.05),
        session_rotation=(0.20, 0.50),
        ip_rotation=(0.20, 0.50),
        instrument_reuse=(0.05, 0.20),
        checkout_completion=(0.05, 0.25),
        continue_after_success=(0.90, 1.00),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="shared",
        login_multiplier=(0.2, 0.8),
        guest=False,
        amount_style_weights={"low": 0.40, "merchant_typical": 0.40, "repeat": 0.20},
        card_diversity_mode="high_rotation",
    ),
    "patient_tester_v4": ScenarioV4(
        name="patient_tester_v4",
        population="attack",
        weight=6.0,
        episodes=(3, 6),
        episode_gap_days=(1.0, 4.0),
        attempts=(1, 3),
        gap_seconds=(300.0, 3600.0),
        gap_spread=(0.50, 1.20),
        method_validity=(0.05, 0.25),
        network_instability=(0.01, 0.05),
        session_rotation=(0.30, 0.70),
        ip_rotation=(0.30, 0.70),
        instrument_reuse=(0.05, 0.20),
        checkout_completion=(0.20, 0.50),
        continue_after_success=(0.80, 0.95),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.5, 1.0),
        guest=False,
        amount_style_weights={"merchant_typical": 0.70, "low": 0.30},
        card_diversity_mode="high_rotation",
    ),
    "ultra_patient_v4": ScenarioV4(
        name="ultra_patient_v4",
        population="attack",
        weight=4.0,
        episodes=(4, 7),
        episode_gap_days=(2.0, 8.0),
        attempts=(1, 2),
        gap_seconds=(600.0, 7200.0),
        gap_spread=(0.60, 1.40),
        method_validity=(0.05, 0.20),
        network_instability=(0.01, 0.05),
        session_rotation=(0.40, 0.80),
        ip_rotation=(0.40, 0.80),
        instrument_reuse=(0.00, 0.15),
        checkout_completion=(0.20, 0.60),
        continue_after_success=(0.80, 0.95),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.6, 1.1),
        guest=False,
        amount_style_weights={"merchant_typical": 0.80, "repeat": 0.20},
        card_diversity_mode="high_rotation",
    ),
    "sparse_multiday_v4": ScenarioV4(
        name="sparse_multiday_v4",
        population="attack",
        weight=4.0,
        episodes=(3, 5),
        episode_gap_days=(1.5, 6.0),
        attempts=(2, 4),
        gap_seconds=(120.0, 1800.0),
        gap_spread=(0.40, 1.00),
        method_validity=(0.04, 0.20),
        network_instability=(0.01, 0.05),
        session_rotation=(0.25, 0.60),
        ip_rotation=(0.25, 0.60),
        instrument_reuse=(0.05, 0.20),
        checkout_completion=(0.15, 0.45),
        continue_after_success=(0.85, 0.98),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.4, 0.9),
        guest=False,
        amount_style_weights={"merchant_typical": 0.60, "low": 0.30, "repeat": 0.10},
        card_diversity_mode="high_rotation",
    ),
    "fast_burst_v4": ScenarioV4(
        name="fast_burst_v4",
        population="attack",
        weight=4.0,
        episodes=(1, 2),
        episode_gap_days=(0.1, 0.8),
        attempts=(5, 12),
        gap_seconds=(1.5, 10.0),
        gap_spread=(0.10, 0.35),
        method_validity=(0.01, 0.10),
        network_instability=(0.01, 0.04),
        session_rotation=(0.10, 0.30),
        ip_rotation=(0.10, 0.30),
        instrument_reuse=(0.00, 0.10),
        checkout_completion=(0.00, 0.10),
        continue_after_success=(0.95, 1.00),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="shared",
        login_multiplier=(0.1, 0.5),
        guest=True,
        amount_style_weights={"low": 0.60, "repeat": 0.40},
        card_diversity_mode="high_rotation",
    ),
    "session_churn_v4": ScenarioV4(
        name="session_churn_v4",
        population="attack",
        weight=4.0,
        episodes=(2, 4),
        episode_gap_days=(0.05, 0.5),
        attempts=(2, 5),
        gap_seconds=(4.0, 25.0),
        gap_spread=(0.15, 0.40),
        method_validity=(0.02, 0.15),
        network_instability=(0.01, 0.05),
        session_rotation=(0.95, 1.00),
        ip_rotation=(0.10, 0.30),
        instrument_reuse=(0.00, 0.10),
        checkout_completion=(0.05, 0.20),
        continue_after_success=(0.90, 1.00),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.0, 0.2),
        guest=True,
        amount_style_weights={"low": 0.70, "merchant_typical": 0.30},
        card_diversity_mode="high_rotation",
    ),
    "success_camouflage_v4": ScenarioV4(
        name="success_camouflage_v4",
        population="attack",
        weight=4.0,
        episodes=(2, 4),
        episode_gap_days=(0.2, 2.0),
        attempts=(3, 6),
        gap_seconds=(20.0, 300.0),
        gap_spread=(0.30, 0.80),
        method_validity=(0.35, 0.65),  # mixed legitimate card
        network_instability=(0.01, 0.05),
        session_rotation=(0.20, 0.50),
        ip_rotation=(0.20, 0.50),
        instrument_reuse=(0.10, 0.30),
        checkout_completion=(0.40, 0.75),
        continue_after_success=(0.85, 0.98),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.7, 1.2),
        guest=False,
        amount_style_weights={"merchant_typical": 0.80, "low": 0.20},
        card_diversity_mode="high_rotation",
    ),
    "merchant_normal_amount_attack_v4": ScenarioV4(
        name="merchant_normal_amount_attack_v4",
        population="attack",
        weight=4.0,
        episodes=(1, 3),
        episode_gap_days=(0.1, 1.0),
        attempts=(3, 7),
        gap_seconds=(10.0, 90.0),
        gap_spread=(0.25, 0.60),
        method_validity=(0.02, 0.15),
        network_instability=(0.01, 0.05),
        session_rotation=(0.30, 0.70),
        ip_rotation=(0.30, 0.70),
        instrument_reuse=(0.05, 0.15),
        checkout_completion=(0.10, 0.30),
        continue_after_success=(0.90, 1.00),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="shared",
        login_multiplier=(0.3, 0.8),
        guest=False,
        amount_style_weights={"merchant_typical": 0.95, "low": 0.05},
        card_diversity_mode="high_rotation",
    ),
    "warm_up_then_attack_v4": ScenarioV4(
        name="warm_up_then_attack_v4",
        population="attack",
        weight=4.0,
        episodes=(2, 3),
        episode_gap_days=(1.0, 5.0),
        attempts=(3, 6),
        gap_seconds=(5.0, 60.0),
        gap_spread=(0.20, 0.50),
        method_validity=(0.10, 0.30),
        network_instability=(0.01, 0.05),
        session_rotation=(0.20, 0.50),
        ip_rotation=(0.20, 0.50),
        instrument_reuse=(0.10, 0.25),
        checkout_completion=(0.30, 0.60),
        continue_after_success=(0.85, 0.98),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.6, 1.1),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "low": 0.15},
        card_diversity_mode="high_rotation",
    ),
    "mixed_campaign_v4": ScenarioV4(
        name="mixed_campaign_v4",
        population="attack",
        weight=4.0,
        episodes=(1, 3),
        episode_gap_days=(0.05, 0.5),
        attempts=(3, 8),
        gap_seconds=(2.0, 30.0),
        gap_spread=(0.15, 0.40),
        method_validity=(0.02, 0.15),
        network_instability=(0.02, 0.06),
        session_rotation=(0.30, 0.70),
        ip_rotation=(0.30, 0.70),
        instrument_reuse=(0.05, 0.15),
        checkout_completion=(0.05, 0.25),
        continue_after_success=(0.90, 1.00),
        devices=(2, 4),
        device_mode="spread",
        customers_on_device=(1, 1),
        ip_pool="shared",
        login_multiplier=(0.2, 0.6),
        guest=True,
        amount_style_weights={"merchant_typical": 0.70, "low": 0.30},
        prefers_campaign=True,
        card_diversity_mode="high_rotation",
    ),
    # --------------------------------------------------------------------------
    # HARD LEGITIMATE NEGATIVE FAMILIES (POST-BLIND REMEDIATION)
    # --------------------------------------------------------------------------
    "subscription_dunning_hard": ScenarioV4(
        name="subscription_dunning_hard",
        population="legitimate",
        weight=12.0,
        episodes=(3, 6),
        episode_gap_days=(0.8, 2.5),  # daily retry
        attempts=(1, 2),
        gap_seconds=(60.0, 300.0),
        gap_spread=(0.20, 0.50),
        method_validity=(0.05, 0.25),  # repeated card decline (expired / balance)
        network_instability=(0.01, 0.03),
        session_rotation=(0.02, 0.10),
        ip_rotation=(0.02, 0.08),
        instrument_reuse=(1.00, 1.00),  # EXACT SAME CARD
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.05, 0.15),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(1.1, 1.3),
        guest=False,
        amount_style_weights={"repeat": 0.90, "merchant_typical": 0.10},
        merchant_kinds=("subscription", "standard_ecommerce"),
        card_diversity_mode="single_card",
        age_pairing="established_burst",
    ),
    "persistent_card_problem_hard": ScenarioV4(
        name="persistent_card_problem_hard",
        population="legitimate",
        weight=10.0,
        episodes=(1, 2),
        episode_gap_days=(0.1, 1.0),
        attempts=(3, 6),
        gap_seconds=(15.0, 180.0),
        gap_spread=(0.30, 0.80),
        method_validity=(0.10, 0.30),  # wrong CVV/expiry or bank decline
        network_instability=(0.01, 0.05),
        session_rotation=(0.05, 0.20),
        ip_rotation=(0.02, 0.10),
        instrument_reuse=(1.00, 1.00),  # EXACT SAME CARD
        checkout_completion=(0.75, 0.95),
        continue_after_success=(0.05, 0.15),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.8, 1.2),
        guest=False,
        amount_style_weights={"repeat": 0.85, "merchant_typical": 0.15},
        card_diversity_mode="single_card",
    ),
    "network_retry_storm_hard": ScenarioV4(
        name="network_retry_storm_hard",
        population="legitimate",
        weight=10.0,
        episodes=(1, 1),
        episode_gap_days=(0.5, 2.0),
        attempts=(4, 7),
        gap_seconds=(1.5, 8.0),  # rapid client auto-retry
        gap_spread=(0.10, 0.25),
        method_validity=(0.15, 0.40),
        network_instability=(0.40, 0.80),
        session_rotation=(0.00, 0.05),
        ip_rotation=(0.00, 0.05),
        instrument_reuse=(1.00, 1.00),  # EXACT SAME CARD
        checkout_completion=(0.70, 0.90),
        continue_after_success=(0.02, 0.10),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.6, 1.1),
        guest=False,
        amount_style_weights={"repeat": 0.95, "merchant_typical": 0.05},
        card_diversity_mode="single_card",
    ),
    "shared_household_device": ScenarioV4(
        name="shared_household_device",
        population="legitimate",
        weight=8.0,
        episodes=(2, 4),
        episode_gap_days=(0.5, 4.0),
        attempts=(1, 3),
        gap_seconds=(60.0, 900.0),
        gap_spread=(0.40, 1.00),
        method_validity=(0.88, 0.98),
        network_instability=(0.01, 0.04),
        session_rotation=(0.30, 0.70),
        ip_rotation=(0.02, 0.10),
        instrument_reuse=(0.70, 0.95),
        checkout_completion=(0.80, 0.98),
        continue_after_success=(0.10, 0.30),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(2, 3),  # shared hardware
        ip_pool="private",
        login_multiplier=(0.9, 1.2),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="wallet_cycle",
    ),
    "cgnat_mobile_ip_storm": ScenarioV4(
        name="cgnat_mobile_ip_storm",
        population="legitimate",
        weight=8.0,
        episodes=(20, 20),
        episode_gap_days=(0.0003, 0.0007),
        attempts=(1, 1),
        gap_seconds=(30.0, 600.0),
        gap_spread=(0.40, 1.10),
        method_validity=(0.85, 0.96),
        network_instability=(0.02, 0.08),
        session_rotation=(0.10, 0.30),
        ip_rotation=(0.00, 0.02),  # all on shared mobile carrier IP
        instrument_reuse=(0.90, 1.00),
        checkout_completion=(0.75, 0.95),
        continue_after_success=(0.05, 0.20),
        devices=(20, 20),
        device_mode="spread",
        customers_on_device=(1, 1),
        ip_pool="mobile",
        login_multiplier=(0.3, 0.8),
        guest=True,
        amount_style_weights={"merchant_typical": 0.85, "low": 0.15},
        card_diversity_mode="single_card",
    ),
    "cvv_and_expiry_mistakes": ScenarioV4(
        name="cvv_and_expiry_mistakes",
        population="legitimate",
        weight=6.0,
        episodes=(1, 2),
        episode_gap_days=(0.2, 2.0),
        attempts=(2, 4),
        gap_seconds=(20.0, 150.0),
        gap_spread=(0.25, 0.60),
        method_validity=(0.30, 0.60),  # mistakes first, then success
        network_instability=(0.01, 0.04),
        session_rotation=(0.02, 0.10),
        ip_rotation=(0.01, 0.05),
        instrument_reuse=(1.00, 1.00),  # same card
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.02, 0.10),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.8, 1.2),
        guest=False,
        amount_style_weights={"repeat": 0.90, "merchant_typical": 0.10},
        card_diversity_mode="single_card",
    ),
    "genuine_wallet_cycling": ScenarioV4(
        name="genuine_wallet_cycling",
        population="legitimate",
        weight=6.0,
        episodes=(1, 2),
        episode_gap_days=(0.1, 1.5),
        attempts=(3, 5),
        gap_seconds=(30.0, 240.0),
        gap_spread=(0.30, 0.70),
        method_validity=(0.25, 0.50),  # first cards decline, final succeeds
        network_instability=(0.01, 0.04),
        session_rotation=(0.05, 0.15),
        ip_rotation=(0.02, 0.08),
        instrument_reuse=(0.20, 0.40),  # cycles 2-3 genuine cards
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.05, 0.15),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.9, 1.2),
        guest=False,
        amount_style_weights={"merchant_typical": 0.90, "repeat": 0.10},
        merchant_kinds=("high_ticket", "standard_ecommerce"),
        card_diversity_mode="wallet_cycle",
    ),
    "session_recreation_flaky_net": ScenarioV4(
        name="session_recreation_flaky_net",
        population="legitimate",
        weight=5.0,
        episodes=(1, 2),
        episode_gap_days=(0.1, 0.8),
        attempts=(2, 4),
        gap_seconds=(15.0, 90.0),
        gap_spread=(0.20, 0.50),
        method_validity=(0.50, 0.80),
        network_instability=(0.30, 0.70),
        session_rotation=(0.75, 1.00),  # browser drops cookie
        ip_rotation=(0.05, 0.20),
        instrument_reuse=(1.00, 1.00),  # same card
        checkout_completion=(0.70, 0.90),
        continue_after_success=(0.02, 0.10),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="mobile",
        login_multiplier=(0.2, 0.6),
        guest=True,
        amount_style_weights={"repeat": 0.85, "merchant_typical": 0.15},
        card_diversity_mode="single_card",
    ),
    "dormant_account_spike": ScenarioV4(
        name="dormant_account_spike",
        population="legitimate",
        weight=4.0,
        episodes=(2, 3),
        episode_gap_days=(15.0, 45.0),  # months dormancy
        attempts=(2, 4),
        gap_seconds=(40.0, 300.0),
        gap_spread=(0.30, 0.80),
        method_validity=(0.40, 0.70),
        network_instability=(0.01, 0.04),
        session_rotation=(0.10, 0.30),
        ip_rotation=(0.05, 0.20),
        instrument_reuse=(0.40, 0.70),
        checkout_completion=(0.80, 0.95),
        continue_after_success=(0.05, 0.15),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(1.0, 1.2),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="wallet_cycle",
        age_pairing="established_burst",
    ),
    # --------------------------------------------------------------------------
    # ORDINARY LEGITIMATE TRAFFIC
    # --------------------------------------------------------------------------
    "normal_returning_customer": ScenarioV4(
        name="normal_returning_customer",
        population="legitimate",
        weight=16.0,
        episodes=(2, 5),
        episode_gap_days=(1.0, 14.0),
        attempts=(1, 2),
        gap_seconds=(60.0, 1200.0),
        gap_spread=(0.40, 1.00),
        method_validity=(0.92, 0.98),
        network_instability=(0.01, 0.03),
        session_rotation=(0.05, 0.15),
        ip_rotation=(0.02, 0.08),
        instrument_reuse=(0.85, 0.98),
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.05, 0.20),
        devices=(1, 2),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(1.0, 1.3),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="single_card",
        age_pairing="natural",
    ),
    "normal_guest_checkout": ScenarioV4(
        name="normal_guest_checkout",
        population="legitimate",
        weight=14.0,
        episodes=(1, 2),
        episode_gap_days=(0.5, 5.0),
        attempts=(1, 2),
        gap_seconds=(45.0, 600.0),
        gap_spread=(0.40, 1.00),
        method_validity=(0.90, 0.97),
        network_instability=(0.01, 0.04),
        session_rotation=(0.10, 0.25),
        ip_rotation=(0.02, 0.10),
        instrument_reuse=(0.90, 1.00),
        checkout_completion=(0.80, 0.95),
        continue_after_success=(0.05, 0.15),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(0.0, 0.0),
        guest=True,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="single_card",
        age_pairing="natural",
    ),
    "new_customer_onboarding": ScenarioV4(
        name="new_customer_onboarding",
        population="legitimate",
        weight=8.0,
        episodes=(1, 2),
        episode_gap_days=(0.2, 3.0),
        attempts=(1, 2),
        gap_seconds=(30.0, 400.0),
        gap_spread=(0.30, 0.80),
        method_validity=(0.90, 0.97),
        network_instability=(0.01, 0.04),
        session_rotation=(0.05, 0.15),
        ip_rotation=(0.02, 0.08),
        instrument_reuse=(0.95, 1.00),
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.05, 0.15),
        devices=(1, 1),
        device_mode="sticky",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(1.0, 1.3),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="single_card",
        age_pairing="new_cust_old_dev",
    ),
    "multi_device_customer_v4": ScenarioV4(
        name="multi_device_customer_v4",
        population="legitimate",
        weight=8.0,
        episodes=(2, 4),
        episode_gap_days=(0.5, 7.0),
        attempts=(1, 2),
        gap_seconds=(40.0, 800.0),
        gap_spread=(0.35, 0.90),
        method_validity=(0.92, 0.98),
        network_instability=(0.01, 0.03),
        session_rotation=(0.15, 0.40),
        ip_rotation=(0.10, 0.30),
        instrument_reuse=(0.80, 0.95),
        checkout_completion=(0.85, 0.98),
        continue_after_success=(0.05, 0.20),
        devices=(2, 3),
        device_mode="spread",
        customers_on_device=(1, 1),
        ip_pool="private",
        login_multiplier=(1.0, 1.3),
        guest=False,
        amount_style_weights={"merchant_typical": 0.85, "repeat": 0.15},
        card_diversity_mode="single_card",
        age_pairing="old_cust_new_dev",
    ),
}
