import { AlertTriangle, ArrowDown, CheckCircle2, ChevronDown, FlaskConical, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { api, friendlyError } from "../lib/api";
import type { BlindMetrics } from "../types";

const percent = (value: number, digits = 1) => `${(value * 100).toFixed(digits)}%`;
const plain = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function EvidencePage() {
  const [metrics, setMetrics] = useState<BlindMetrics | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.blindMetrics<BlindMetrics>().then((result) => result.status === "available" ? setMetrics(result) : setError(result.reason || "Evaluation is unavailable")).catch((reason) => setError(friendlyError(reason))); }, []);
  return <main className="results-page">
    <header className="results-hero page-width"><span className="eyebrow-pill"><i/>Public prototype results</span><h1>Promising detection, <em>but not ready for production.</em></h1><p>This benchmark uses synthetic traffic. The figures below come directly from the published evaluation API and include the customer-friction cost, not just the attacks Sentinel caught.</p></header>
    {error && <div className="evidence-error page-width"><AlertTriangle/>{error}</div>}
    {!metrics && !error && <div className="evidence-loading page-width"><i/>Loading current evaluation results…</div>}
    {metrics && <>
      <section className="headline-results page-width" aria-label="Headline results">{[
        ["Attack attempts interrupted", metrics.headline.attack_intervention_rate, "Reviewed or temporarily blocked", "good"],
        ["Attack attempts temporarily blocked", metrics.headline.attack_block_rate, "Stopped before order creation", "good"],
        ["Legitimate attempts interrupted", metrics.headline.legitimate_intervention_rate, "Customer friction that needs improvement", "warn"],
        ["Legitimate attempts temporarily blocked", metrics.headline.legitimate_block_rate, "The most costly false positives", "bad"],
      ].map(([label, value, note, tone]) => <article key={String(label)} className={String(tone)}><span>{String(label)}</span><strong>{percent(Number(value))}</strong><div className="metric-track"><i style={{ width: percent(Number(value)) }}/></div><p>{String(note)}</p></article>)}</section>
      <p className="results-disclaimer page-width"><FlaskConical/>These are synthetic evaluation results, not measured production fraud performance.</p>
      <section className="results-story page-width"><article className="strength"><CheckCircle2/><span>What worked</span><h2>Many fast, repeated attacks accumulated enough evidence.</h2><p>Intervention was strongest in visible high-velocity patterns. Detection by attempt rose as behavioural history accumulated.</p><div className="detection-list">{Object.entries(metrics.detection_by_attempt).map(([attempt, value]) => <div key={attempt}><span>By attempt {attempt}</span><strong>{percent(value, 0)}</strong></div>)}</div></article><article className="weakness"><ShieldAlert/><span>What did not</span><h2>Patient attacks and genuine retries remain hard to separate.</h2><p>Hardest attack patterns: {metrics.limitations.hardest_attacks.map(plain).join(" and ")}. Highest legitimate friction: {metrics.limitations.highest_friction.map(plain).join(" and ")}.</p><p className="limitation-summary">{metrics.limitations.summary}</p></article></section>
      <section className="learning-section"><div className="page-width"><header><span>Iteration story</span><h2>Initial approach → what we learned → current approach</h2></header><div className="learning-grid"><article><b>01</b><h3>Initial approach</h3><p>Optimise aggressively for detecting synthetic card-testing sequences.</p></article><ArrowDown/><article><b>02</b><h3>What we learned</h3><p>Strong intervention can also punish legitimate decline streaks and unusual but genuine retries.</p></article><ArrowDown/><article><b>03</b><h3>Current approach</h3><p>Report both detection and friction, keep actions bounded, and treat the current model as a prototype.</p></article></div><p className="why-dropped"><strong>Why headline performance dropped:</strong> the later benchmark was deliberately stricter and exposed harder attack patterns alongside more realistic legitimate failure behaviour. That makes the result more useful, even when the numbers look worse.</p></div></section>
      <section className="method-section page-width"><header><span>Methodology</span><h2>How to read these results</h2></header><div><article><b>{metrics.active_device_counts.attack}</b><span>Synthetic attack devices</span></article><article><b>{metrics.active_device_counts.legitimate}</b><span>Synthetic legitimate devices</span></article><article><b>{Object.values(metrics.operating_targets).filter((value) => value === "PASS").length}</b><span>Operating targets passed</span></article><article><b>{Object.values(metrics.operating_targets).filter((value) => value === "FAIL").length}</b><span>Operating targets failed</span></article></div><p>{metrics.disclosure}</p></section>
      <section className="next-section page-width"><header><span>Next improvements</span><h2>What would make this safer.</h2></header><ol><li>Reduce false positives around genuine decline streaks.</li><li>Improve long-horizon detection for patient, low-rate attacks.</li><li>Validate thresholds with representative merchant traffic.</li><li>Add production monitoring, appeal and rollback controls.</li></ol></section>
      <details className="technical-details page-width"><summary>Technical details <ChevronDown/></summary><div><dl><div><dt>Evaluation source</dt><dd>{metrics.source}</dd></div><div><dt>Model ranking: precision–recall area</dt><dd>{metrics.model_metrics.pr_auc.toFixed(6)}</dd></div><div><dt>Model ranking: receiver operating area</dt><dd>{metrics.model_metrics.roc_auc.toFixed(6)}</dd></div><div><dt>Calibration error</dt><dd>{metrics.model_metrics.ece.toFixed(6)}</dd></div><div><dt>Evaluation verdict</dt><dd>{metrics.verdict}</dd></div></dl><h3>Operating targets</h3><ul>{Object.entries(metrics.operating_targets).map(([name, value]) => <li key={name}><span>{plain(name)}</span><strong className={value.toLowerCase()}>{value}</strong></li>)}</ul><p>{metrics.replay.reason}</p></div></details>
    </>}
  </main>;
}
