import { AlertTriangle, CheckCircle2, ChevronDown, FlaskConical, Search, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import { EvaluationCharts } from "../components/EvaluationCharts";
import { api, friendlyError } from "../lib/api";
import type { BlindMetrics } from "../types";

const percent=(value:number)=>`${(value*100).toFixed(2)}%`;
const plain=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase()).replace(" V2","");

export function EvidencePage(){
 const [metrics,setMetrics]=useState<BlindMetrics|null>(null); const [error,setError]=useState("");
 useEffect(()=>{api.blindMetrics<BlindMetrics>().then(result=>result.status==="available"?setMetrics(result):setError(result.reason||"Evaluation is unavailable")).catch(reason=>setError(friendlyError(reason)))},[]);
 return <main className="results-page"><header className="results-hero page-width"><span className="eyebrow-pill"><i/>Synthetic benchmark</span><h1>Current evaluation results</h1><p>Sentinel performed best on rapid, repeated card-testing behaviour. Genuine retry-heavy behaviour and slow, weakly connected attacks remain more difficult.</p></header>
 {error&&<div className="evidence-error page-width"><AlertTriangle/>{error}</div>}{!metrics&&!error&&<div className="evidence-loading page-width"><i/>Loading current evaluation results…</div>}
 {metrics&&<>
  <section className="profile-explainer page-width"><FlaskConical/><p><strong>These are profile-level results.</strong> One test profile represents a synthetic device’s behaviour across multiple payment attempts.</p></section>
  <section className="headline-results page-width" aria-label="Headline evaluation rates">{[
   ["Risky test profiles identified",metrics.headline.attack_intervention_rate,"Reviewed or temporarily blocked","good"],
   ["Risky test profiles temporarily blocked",metrics.headline.attack_block_rate,"Stopped before order creation","good"],
   ["Genuine test profiles interrupted",metrics.headline.legitimate_intervention_rate,"Customer friction to reduce","warn"],
   ["Genuine test profiles temporarily blocked incorrectly",metrics.headline.legitimate_block_rate,"Highest-cost false positives","bad"],
  ].map(([label,value,note,tone])=><article key={String(label)} className={String(tone)}><span>{String(label)}</span><strong>{Math.round(Number(value)*100)} <small>out of 100</small></strong><b>{percent(Number(value))}</b><div className="metric-track"><i style={{width:percent(Number(value))}}/></div><p>{String(note)}</p></article>)}</section>
  <p className="results-disclaimer page-width"><FlaskConical/>{metrics.disclosure}</p>
  <EvaluationCharts metrics={metrics}/>
  <section className="scenario-section page-width"><header><span>Evaluated synthetic scenarios</span><h2>Where Sentinel can help</h2><p>These examples are supported by committed scenario results; they are not claims about production traffic.</p></header><div className="scenario-result-grid">{metrics.scenario_metrics.filter(row=>row.population==="attack").sort((a,b)=>b.intervention_rate-a.intervention_rate).slice(0,4).map(row=><article key={row.scenario}><CheckCircle2/><h3>{plain(row.scenario)}</h3><p>Repeated or connected activity becomes visible across the profile.</p><dl><div><dt>Profiles identified</dt><dd>{percent(row.intervention_rate)}</dd></div><div><dt>Temporarily blocked</dt><dd>{percent(row.block_rate)}</dd></div></dl><small>{row.block_rate>0?"Some profiles stopped before order creation.":"Intervention did not require a temporary block."}</small></article>)}</div></section>
  <section className="scenario-section needs-evidence"><div className="page-width"><header><span>Ambiguous evaluated scenarios</span><h2>Where Sentinel needs more evidence</h2><p>Selection rule: the API’s named hardest attacks and highest-friction genuine scenarios.</p></header><div className="scenario-result-grid">{[...metrics.limitations.hardest_attacks.map(name=>[name,"attack"] as const),...metrics.limitations.highest_friction.map(name=>[name,"legitimate"] as const)].map(([name,population])=>{const row=metrics.scenario_metrics.find(item=>item.scenario===name);return <article key={name}><ShieldAlert/><h3>{plain(name)}</h3><p>{population==="legitimate"?"Genuine retry-heavy behaviour can resemble abuse and create customer friction.":"Slow or weakly connected behaviour may not accumulate enough evidence quickly."}</p>{row&&<dl><div><dt>{population==="legitimate"?"Profiles interrupted":"Profiles identified"}</dt><dd>{percent(row.intervention_rate)}</dd></div><div><dt>Temporarily blocked</dt><dd>{percent(row.block_rate)}</dd></div></dl>}<small>{population==="legitimate"?"Thresholds and context need improvement.":"Stronger cross-device evidence is needed."}</small></article>})}</div></div></section>
  <section className="evaluation-evolution page-width"><Search/><div><span>How the evaluation became more realistic</span><h2>Harder scenarios, more honest friction reporting.</h2><p><strong>Initial approach:</strong> demonstrated that behavioural history could expose card testing, but used an easier experimental setup and underrepresented difficult genuine retries.</p><p><strong>Current approach:</strong> uses 39 pre-authorization signals, fixed decision rules, separate harder scenarios and customer-friction reporting alongside detection.</p><p className="evolution-note">Lower headline numbers do not automatically prove that the current model is more accurate. They reflect a stricter and more representative evaluation.</p></div></section>
  <details className="technical-details page-width"><summary>Technical details <ChevronDown/></summary><div><p><strong>Internal evaluation gate: {metrics.verdict}.</strong> This means the current system missed predefined customer-friction targets. It is not a general rating of the complete project.</p><dl><div><dt>Evaluation source</dt><dd>{metrics.source}</dd></div><div><dt>Precision–recall area</dt><dd>{metrics.model_metrics.pr_auc.toFixed(6)}</dd></div><div><dt>Receiver operating area</dt><dd>{metrics.model_metrics.roc_auc.toFixed(6)}</dd></div><div><dt>Calibration error</dt><dd>{metrics.model_metrics.ece.toFixed(6)}</dd></div></dl><h3>Operating targets</h3><ul>{Object.entries(metrics.operating_targets).map(([name,value])=><li key={name}><span>{plain(name)}</span><strong className={value.toLowerCase()}>{value}</strong></li>)}</ul><p>{metrics.replay.reason}</p></div></details>
 </>}</main>;
}
