import { AlertTriangle, CheckCircle2, CreditCard, Eye, Gauge, GitBranch, History, Server, ShieldCheck, Shuffle, XCircle } from "lucide-react";
import { useRef, useState } from "react";

type Story = "normal" | "burst" | "retry";
const storyOrder: Story[] = ["normal", "burst", "retry"];
const stories = {
  normal: { tab: "Normal purchase", person: "Rahul", heading: "One familiar purchase, one clean path.", intro: "Rahul wants to buy headphones for ₹2,499 from a test store. He uses his usual device and makes one payment attempt.", outcome: "ALLOW — Razorpay order creation permitted", tone: "allow", icon: CheckCircle2, signals: ["One payment attempt", "Usual protected device context", "No suspicious retry sequence"], steps: ["Rahul clicks Pay", "Sentinel checks recent merchant-visible behaviour", "No suspicious pattern has accumulated", "Sentinel returns ALLOW", "The backend creates a Razorpay Test order", "Razorpay Checkout opens", "Success is trusted only after backend verification"] },
  burst: { tab: "Card-testing burst", person: "Automated actor", heading: "Small attempts become a visible sequence.", intro: "An automated actor starts with ₹2 and ₹5 attempts and rapidly tries several protected card references.", outcome: "ALLOW → REVIEW → TEMPORARY BLOCK", tone: "block", icon: Shuffle, signals: ["Attempt velocity rises", "Protected card references change", "Declines and session changes accumulate"], steps: ["The first attempt contains limited evidence", "Repeated attempts accumulate", "Card-reference diversity increases", "Declines and session changes add evidence", "The decision can progress from ALLOW to REVIEW and TEMPORARY BLOCK", "REVIEW and BLOCK prevent Razorpay order creation"] },
  retry: { tab: "Difficult genuine retry", person: "Priya", heading: "Genuine failure can resemble abuse.", intro: "Priya’s genuine card is failing because of a bank or network issue, so she retries several times.", outcome: "Possible REVIEW — more evidence is needed", tone: "review", icon: AlertTriangle, signals: ["Retry velocity increases", "Verified declines accumulate", "Intent remains difficult to distinguish"], steps: ["Priya is a genuine customer", "Repeated failures increase velocity and decline-history signals", "The pattern can resemble card testing", "Sentinel may interrupt the attempt", "Reducing this customer friction is a future improvement"] },
} as const;
const technical = [[CreditCard,"Customer clicks Pay"],[Server,"Merchant backend sends payment context"],[Gauge,"Sentinel constructs 39 ordered signals"],[ShieldCheck,"Risk model scores the attempt"],[GitBranch,"Policy returns a bounded decision"],[CheckCircle2,"ALLOW permits order creation"],[XCircle,"REVIEW and BLOCK stop before the order"],[History,"Verified outcomes update future history"]] as const;

export function HowItWorksPage() {
  const [active, setActive] = useState<Story>("normal"); const tabs = useRef<Array<HTMLButtonElement | null>>([]);
  function keydown(event: React.KeyboardEvent, index: number) { let next=index; if(event.key==="ArrowRight") next=(index+1)%3; else if(event.key==="ArrowLeft") next=(index+2)%3; else if(event.key==="Home") next=0; else if(event.key==="End") next=2; else return; event.preventDefault(); setActive(storyOrder[next]); tabs.current[next]?.focus(); }
  const story=stories[active]; const StoryIcon=story.icon;
  return <main className="how-page story-page">
    <header className="page-hero page-width"><span className="eyebrow-pill"><i/>Three payment stories</span><h1>Understand Sentinel <em>without learning the machinery first.</em></h1><p>Follow a normal purchase, a rapid card-testing sequence and a difficult genuine retry. Then open the technical path underneath.</p></header>
    <section className="story-explorer page-width"><div className="story-tabs" role="tablist" aria-label="Payment stories">{storyOrder.map((name,index)=><button key={name} ref={node=>{tabs.current[index]=node}} role="tab" aria-selected={active===name} aria-controls={`story-${name}`} tabIndex={active===name?0:-1} onClick={()=>setActive(name)} onKeyDown={event=>keydown(event,index)}>{stories[name].tab}</button>)}</div><article className={`story-panel ${story.tone}`} id={`story-${active}`} role="tabpanel"><div className="story-intro"><span>{story.person}</span><h2>{story.heading}</h2><p>{story.intro}</p><div className="story-signal-list">{story.signals.map(signal=><span key={signal}><i/>{signal}</span>)}</div><div className="story-outcome"><StoryIcon/><span>Outcome</span><strong>{story.outcome}</strong></div></div><ol className="story-steps">{story.steps.map((step,index)=><li key={step}><b>{index+1}</b><span>{step}</span></li>)}</ol></article></section>
    <section className="technical-flow-section"><div className="page-width"><header><span>For evaluators</span><h2>The complete technical flow.</h2><p>Every step remains responsive and uses information available at that point in the payment lifecycle.</p></header><ol className="technical-flow">{technical.map(([Icon,label],index)=><li key={label}><b>{index+1}</b><Icon/><span>{label}</span></li>)}</ol><div className="flow-accuracy"><article><CheckCircle2/><strong>After ALLOW</strong><p>Order creation is permitted; payment authorization has not happened yet.</p></article><article><Eye/><strong>After REVIEW</strong><p>Merchant intervention is recommended; no extra verification workflow is implemented.</p></article><article><XCircle/><strong>After TEMPORARY BLOCK</strong><p>This attempt stops before Razorpay without permanently banning the customer.</p></article></div></div></section>
  </main>;
}
