"""Repository protocol for live lifecycle state."""

from __future__ import annotations

from typing import Protocol

from card_testing_sentinel.persistence.models import StoredEvent, StoredRequest


class StateRepository(Protocol):
    store_type: str

    def initialize(self) -> None: ...

    def close(self) -> None: ...

    def get_request(self, request_id: str) -> StoredRequest | None: ...

    def get_request_by_event(self, event_id: str) -> StoredRequest | None: ...

    def get_event(self, event_id: str) -> StoredEvent | None: ...

    def get_event_for_request(
        self, request_id: str, event_type: str
    ) -> StoredEvent | None: ...

    def save_request(self, request: StoredRequest) -> None: ...

    def save_event(self, event: StoredEvent) -> None: ...

    def requests_in_order(self) -> list[StoredRequest]: ...

    def events_in_order(self) -> list[StoredEvent]: ...

    def latest_order(self) -> tuple[str, int] | None: ...

    def decisions(self, limit: int) -> list[dict]: ...

    def device_timeline(self, device_hash: str) -> list[dict]: ...

    def status(self) -> dict: ...
